# Generated by Django 2.2 on 2021-02-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keycloakuser',
            old_name='keycloak_id',
            new_name='id',
        ),
    ]
