# Generated by Django 2.2 on 2021-04-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0002_auto_20210209_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keycloakuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
