# Generated by Django 2.2 on 2021-12-31 11:16

from django.db import migrations, models
import django_keycloak.managers


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("django_keycloak", "0003_auto_20210406_1426"),
    ]
