# Generated by Django 2.2 on 2021-12-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_keycloak", "0004_keycloakuserautoid"),
    ]
